### ISSUE TITLE
Add support for email as username

### ISSUE THREAD

**Issue by kasparsd** [WordPress/application-passwords#104]
See https://wordpress.org/support/topic/email-instead-of-userid-in-rest-request/

> However, requests take a userid and not an email address. Email addresses have become a default standard for logons.

**Comment by kasparsd** [comment]
It should actually work already:

https://github.com/WordPress/application-passwords/blob/0e71ecdad32eb54c7bfebac0553482e72f3134aa/class.application-passwords.php#L361-L365

**Comment by kasparsd** [comment]
Should have been fixed in #104.

**Comment by BrianHenryIE** [comment]
This is 104, you mean #77

**Comment by kasparsd** [comment]
Closing until we know exactly how to replicate this.
