### ISSUE TITLE
Plugin could not be activated because it triggered a fatal error.

### ISSUE THREAD

**Issue by bjohas** [WordPress/application-passwords#115]
Hello,

when I install the plugin from within a Wordpress install (latest version, latest stable PHP), I get:
```
Plugin could not be activated because it triggered a fatal error.
Fatal error: Cannot declare class Application_Passwords, because the name is already in use in /srv/data/web/vhosts/convet.org/htdocs/wp-content/plugins/application-passwords/class.application-passwords.php on line 9
```
Any tips?

Thanks!!!

**Comment by jeffpaul** [comment]
@bjohas I just tried installing Application Passwords on a WordPress 5.5.1 install running PHP 7.3.5 and do not have issues activating the plugin.  Mind sharing the export from your Site Health Info so others can try to replicate your issue and better assist?

**Comment by kasparsd** [comment]
@bjohas Could there be another instance active of this same plugin under the must-use plugins, for example? Searching for `Application_Passwords` from the root of your WP instance could help identify this.

**Comment by bjohas** [comment]
@kasparsd - thanks for the comment!

There's nothing relating to `Application_Passwords`. However, I've got these two
```
./wp-content/plugins/application-passwords/class.application-passwords.php
./wp-content/plugins/distributor-stable/vendor/georgestephanis/application-passwords/class.application-passwords.php
```
(and other files in those dirs).

Does that look ok?

**Comment by kasparsd** [comment]
@bjohas Looks like you have the Distributor plugin https://github.com/10up/distributor installed which bundles the this plugin already. That means you can't have the standalone version of the same plugin installed as long as the Distributor plugin is active.
