### ISSUE TITLE
The responsive list table doesn't kick in immediately after passwords are added.

### ISSUE THREAD

**Issue by TimothyBJacobs** [WordPress/application-passwords#117]
If you create a new App Password while on mobile, the new row is added to the table, but it cannot be expanded to see the full details. After refreshing the page, it functions as expected.

![image](https://user-images.githubusercontent.com/3460448/94284386-47641880-ff20-11ea-99ef-fa0e07fb2948.png)

![image](https://user-images.githubusercontent.com/3460448/94284396-49c67280-ff20-11ea-9dc4-9e07e7d8e3d1.png)

PRs should be opened in https://github.com/georgestephanis/wordpress-develop/tree/add/application-passwords.

**Comment by jeffpaul** [comment]
As noted in Slack, I'm looking to find someone to help on this but if someone else has interest in the meantime please go for it!
