### ISSUE TITLE
Revoking Passwords: Should we have a confirmation dialog

### ISSUE THREAD

**Issue by kjbenk** [WordPress/application-passwords#17]
Currently there is no confirmation dialog for revoking a password.  This can lead to accidental password revoking.  This is especially bad for the revoking all application passwords button.  At a minimum this should have a confirmation dialog.

**Comment by JeffMatson** [comment]
I agree.  Your password creation modal was just merged.  Go ahead and handle this the same way.

**Comment by kjbenk** [comment]
Can you please assign it to me :)

**Comment by JeffMatson** [comment]
Oddly, I cannot?

Consider this an informal assignment.
