### ISSUE TITLE
Add a new password programmatically?

### ISSUE THREAD

**Issue by JohnDeeBDD** [WordPress/application-passwords#81]
Is there a way to create a password and get the secret response programmatically? This would be very useful for plugin developers who want to automate the process or have the interaction happen in a different UI [like a theme].

i.e.:
`$secret = createNewAppPassword($someAppName, $someUserID);`

I didn't look through the code... maybe this can already be done.

**Comment by BrianHenryIE** [comment]
https://github.com/georgestephanis/application-passwords/blob/master/class.application-passwords.php#L630-L663

`$new_application_password = Application_Passwords::create_new_application_password( 1, 'Test Password' );`

```
["sWIGEdWtuo2vJCdPtZjWEd4u", {
	"name": "Test Password",
	"password": "$P$BHD4BcDl3EBERpadOaf3Bm77pHeeEl\/",
	"created": 1547001715,
	"last_used": null,
	"last_ip": null
}]
```

`$new_application_password[0]` is your password.
